### 

POST http://localhost:8082/teachers HTTP/1.1
Content-Type: application/json
Accept: application/json

{
  "teachers": [
    {
      "class": "20B1",
      "email": "alice1@abv.bg",
      "first_name": "Alice1",
      "last_name": "Brown1",
      "subject": "World Jistory1"
    },
    {
      "class": "8C1",
      "email": "bob1@abv.bg",
      "first_name": "Bob1",
      "last_name": "White1",
      "subject": "Math"
    }
  ]
}
